Create assignment page (Tutor)
tryyang2001/CS3213-Frontend-Management-System pull request #25
Opened 2024-03-02 18:02 UTC by junhonglow

## Description
Create the frontend page under /assignments/create route that will display a page for tutors to create an assignment. There is currently no limit on the number of questions that can be created for an assignment.

## Related Issue(s)
Partially completes #3, will close after PR #24 is merged as well.

## Screenshots
![image](https://github.com/tryyang2001/CS3213-Frontend-Management-System/assets/95668366/2746b06a-8b0d-4b36-8288-6c317e502a6d)

## Additional Notes
1. Added a change to layout, currently if the components exceeded the scroll height of the window, the background would revert back to black.

2. ![image](https://github.com/tryyang2001/CS3213-Frontend-Management-System/assets/95668366/3424261d-57bc-48ba-b801-88db76489c0d)
There's a supposed [issue](https://github.com/nextui-org/nextui/pull/2371) that is linked with the input type for date and time for Next UI that has supposedly been fixed in v2.1.17 but not sure why it's still occurring. Either way, I have a workaround but it is not the best looking.

2024-03-08 04:03 UTC, WillCWX requested changes
Good work

There are some comments regarding the handling of inputs.

Do you have a way to handle the submission? It seems that the inputs are not controlled so you can't submit the values directly. There is no overall `<form>` also so I'm not sure how submission will work.

2024-03-17 17:00 UTC, junhonglow commented
Issues have been resolved.

2024-03-18 08:27 UTC, WillCWX approved these changes
Looks good to me!

Just change `{AssignmentCreator()}` to `<AssignmentCreator />` and fix the merge conflicts.

We may need to breakdown the pages into smaller components soon but this should be fine for now.

2024-03-18 08:27 UTC, WillCWX commented on frontend/src/app/layout.tsx
> +          <div className="h-screen flex flex-row justify-start">
i think you have some conflicts with master that vivien just merged in

2024-03-18 08:27 UTC, WillCWX commented on frontend/src/components/forms/AssignmentCreator.tsx
> +            {renderQuestionUploads()}
This one is ok as it is a render (no react hooks)

2024-03-18 08:27 UTC, WillCWX commented on frontend/src/components/FileUpload.tsx
> +            {renderPreview()}
This one is ok as it is a render (no react hooks)

2024-03-18 13:47 UTC, tryyang2001 commented
@junhonglow can you fix the build error in frontend? You may see the errors by running `yarn build` locally, and fix those "error" (I think warning is fine for now)

2024-03-18 14:20 UTC, merged